version: "3"

services:
  next-app:
    container_name: next-app
    build:
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
    #   POSTGRES_HOST: ${POSTGRES_HOST}
    #   POSTGRES_PORT: ${POSTGRES_PORT}
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
    #   POSTGRES_URL_NON_POOLING: ${POSTGRES_URL_NON_POOLING}
    #   PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    #   PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    #   PORT: ${PORT}

    # Set environment variables based on the .env file
    env_file:
      - .env
      - .env.local
    volumes:
      - ./:/app/src
      # - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true